=== xburv005/Adresar/vbures.xsd
<!-- Odkaz na github: https://github.com/xburv005/Adresar --> 
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Adresar_konfigurace">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nastaveni-obecne"> <!-- Obecné nastavení -->       
          <xs:complexType>
            <xs:sequence>
              <xs:element type="chars" name="charset"/>
              <xs:element type="jaz" name="jazyk"/>
              <xs:element type="vypzap" name="javascript"/>
              <xs:element type="vypzap" name="vbscript"/>
              <xs:element name="nastaveni-moduly">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="vypzap" name="komentare"/>
                    <xs:element type="vypzap" name="vyhledavani"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="prot" name="protokol"/>
              <xs:element type="xs:string" name="omezeni-pristupu"/>
              <xs:element type="email" name="kontakt-admin"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- Konec obecného nastavení -->
        <xs:element name="tabulka-prav"> <!-- Nastavení práv --> 
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Pravo" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="oprav" name="prava"/>
                    <xs:element type="vypzap" name="cteni"/>
                    <xs:element type="vypzap" name="zapis"/>
                    <xs:element type="vypzap" name="pridavani"/>
                    <xs:element type="vypzap" name="mazani"/>
                    <xs:element type="vypzap" name="sprava-uziv"/>
                    <xs:element type="vypzap" name="uprava-sekci"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="Jmeno" use="required"/>
                  <xs:attribute type="xs:string" name="Prikaz" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- Konec Nastavení práv --> 
        <xs:element name="Adresar" maxOccurs="unbounded" minOccurs="0"> <!-- Nastavení práv Adresáře --> 
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="pocet-zaznamu-na-soubor"/>
              <xs:element type="pop" name="Popis"/>
              <xs:element name="Pristupova-prava">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="osoba" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Jmeno"/>
                          <xs:element type="xs:string" name="Prijmeni"/>
                          <xs:element type="xs:string" name="Prihl-jmeno"/>
                          <xs:element type="oprav" name="Pravomoce"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id" use="required"/>
                        <xs:attribute type="xs:byte" name="Kod" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="Nazev" use="required"/>
            <xs:attribute type="xs:string" name="Disk" use="required"/>
          </xs:complexType>
        </xs:element> <!-- Konec nastavení  práv adresáře --> 
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Nastavení omezení -->
  <xs:simpleType name="vypzap"> <!-- Omezení zapnuto/vypnuto -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="chars"> <!-- Omezení nastavení charsetu -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="utf-8"/>
      <xs:enumeration value="windows-1258"/>
      <xs:enumeration value="utf-7"/>
      <xs:enumeration value="iso-8859"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="jaz"> <!-- Omezení nastavení jazyku -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="CZ"/>
      <xs:enumeration value="EN"/>
      <xs:enumeration value="US"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="prot"> <!-- Omezení nastavení protokolů -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="http"/>
      <xs:enumeration value="https"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="email"> <!-- Omezení nastavení emailových adres -->
    <xs:restriction base="xs:string">
       <xs:pattern value="[^@]+@[^\.]+\..+"/> <!-- Regex pro rozpoznání emailové adresy -->
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="oprav"><!-- Omezení nastavení oprávnění-->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="3"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="pop"><!-- Omezení nastavení popisu sekce-->
    <xs:restriction base="xs:string">
    	<xs:minLength value="5"/>
      	<xs:maxLength value="150"/>
    </xs:restriction>
  </xs:simpleType> 
</xs:schema>

=== xburv005/Adresar/vbures.xml
<?xml version="1.0" encoding="utf-8"?>
  <?xml-stylesheet type="text/xsl" href="vbures.xsl"?>
  <!-- Odkaz na github: https://github.com/xburv005/Adresar --> 
<Adresar_konfigurace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vbures.xsd">

<!-- Obecné nastavení -->
<nastaveni-obecne>
	<charset>utf-8</charset>
	<jazyk>CZ</jazyk>
	<javascript>1</javascript>
	<vbscript>0</vbscript>
	<nastaveni-moduly>
		<komentare>1</komentare>
		<vyhledavani>1</vyhledavani>
	</nastaveni-moduly>
	<protokol>http</protokol>
	<omezeni-pristupu></omezeni-pristupu>	
	<kontakt-admin>admin@admin.cz</kontakt-admin>
</nastaveni-obecne>

<!-- Nastavení práv uživatelů -->
<tabulka-prav>
	<Pravo Jmeno="dělník"  Prikaz="CTENI">
		<prava>0</prava>
		<cteni>1</cteni>
		<zapis>0</zapis>
		<pridavani>0</pridavani>
		<mazani>0</mazani>
		<sprava-uziv>0</sprava-uziv>
		<uprava-sekci>0</uprava-sekci>
	</Pravo>
	<Pravo Jmeno="Mistr" Prikaz="CTENI A ZAPIS">
		<prava>1</prava>
		<cteni>1</cteni>
		<zapis>1</zapis>
		<pridavani>0</pridavani>
		<mazani>0</mazani>
		<sprava-uziv>0</sprava-uziv>
		<uprava-sekci>0</uprava-sekci>
	</Pravo>
	<Pravo Jmeno="správce" Prikaz="ZMENA UZIVATELE">
		<prava>2</prava>
		<cteni>1</cteni>
		<zapis>0</zapis>
		<pridavani>1</pridavani>
		<mazani>1</mazani>
		<sprava-uziv>1</sprava-uziv>
		<uprava-sekci>0</uprava-sekci>
	</Pravo>
	<Pravo Jmeno="Administrátor" Prikaz="ADMINISTRACE">
		<prava>3</prava>
		<cteni>1</cteni>
		<zapis>1</zapis>
		<pridavani>1</pridavani>
		<mazani>1</mazani>
		<sprava-uziv>1</sprava-uziv>
		<uprava-sekci>1</uprava-sekci>
	</Pravo>
</tabulka-prav>

<!-- Adresář PZ -->
  <Oddeleni Nazev="Přijaté zakázky"  Disk="I">
  	<pocet-zaznamu-na-soubor>25</pocet-zaznamu-na-soubor>
  	<Popis>Seznam přijatých zakázek.</Popis>
  		<Pristupova-prava>
  			<osoba id="0" Kod="0000">
  				<Jmeno>Návštěvník</Jmeno>
  				<Prijmeni></Prijmeni>
  				<Prihl-jmeno>guest</Prihl-jmeno>
  				<Pravomoce>0</Pravomoce>
  			</osoba>
  			<osoba id="1" Kod="0001">
  				<Jmeno>Martin</Jmeno>
  				<Prijmeni>Beneš</Prijmeni>
  				<Prihl-jmeno>admin</Prihl-jmeno>
  				<Pravomoce>3</Pravomoce>
  			</osoba>
  			<osoba id="2" Kod="0002">
  				<Jmeno>Petra</Jmeno>
  				<Prijmeni>Suchá</Prijmeni>
  				<Prihl-jmeno>suchap</Prihl-jmeno>
  				<Pravomoce>2</Pravomoce>
  			</osoba>
  			<osoba id="3" Kod="0003">
  				<Jmeno>Petr</Jmeno>
  				<Prijmeni>Šulc</Prijmeni>
  				<Prihl-jmeno>sulcp</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  			<osoba id="4" Kod="0004">
  				<Jmeno>Milan</Jmeno>
  				<Prijmeni>Macko</Prijmeni>
  				<Prihl-jmeno>mackm</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  		</Pristupova-prava>
  </Oddeleni>

  <!-- Adresář VZ -->
  <Oddeleni Nazev="Vyřešené zakázky"  Disk="I">
  	<pocet-zaznamu-na-soubor>25</pocet-zaznamu-na-soubor>
  	<Popis>Zakázky které již byli vyřešeny.</Popis>
  		<Pristupova-prava>
  			<osoba id="0" Kod="0000">
  				<Jmeno>Návštěvník</Jmeno>
  				<Prijmeni></Prijmeni>
  				<Prihl-jmeno>guest</Prihl-jmeno>
  				<Pravomoce>0</Pravomoce>
  			</osoba>
  			<osoba id="1" Kod="0001">
  				<Jmeno>Martin</Jmeno>
  				<Prijmeni>Beneš</Prijmeni>
  				<Prihl-jmeno>admin</Prihl-jmeno>
  				<Pravomoce>3</Pravomoce>
  			</osoba>
  			<osoba id="2" Kod="0005">
  				<Jmeno>Jitka</Jmeno>
  				<Prijmeni>Levá</Prijmeni>
  				<Prihl-jmeno>levaj</Prihl-jmeno>
  				<Pravomoce>2</Pravomoce>
  			</osoba>
  			<osoba id="3" Kod="0006">
  				<Jmeno>Miroslav</Jmeno>
  				<Prijmeni>Páka</Prijmeni>
  				<Prihl-jmeno>mirop</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  			<osoba id="4" Kod="0007">
  				<Jmeno>Pavlína</Jmeno>
  				<Prijmeni>Světlá</Prijmeni>
  				<Prihl-jmeno>svetp</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  		</Pristupova-prava>
  </Oddeleni>

  <!-- Adresář RE -->
  <Oddeleni Nazev="Reklamace"  Disk="I">
  	<pocet-zaznamu-na-soubor>25</pocet-zaznamu-na-soubor>
  	<Popis>Zakázky které byli reklamované</Popis>
  		<Pristupova-prava>
  			<osoba id="0" Kod="0000">
  				<Jmeno>Návštěvník</Jmeno>
  				<Prijmeni></Prijmeni>
  				<Prihl-jmeno>guest</Prihl-jmeno>
  				<Pravomoce>0</Pravomoce>
  			</osoba>
  			<osoba id="1" Kod="0001">
  				<Jmeno>Martin</Jmeno>
  				<Prijmeni>Beneš</Prijmeni>
  				<Prihl-jmeno>admin</Prihl-jmeno>
  				<Pravomoce>3</Pravomoce>
        </osoba>
  			<osoba id="2" Kod="0008">
  				<Jmeno>Libuše</Jmeno>
  				<Prijmeni>Jirásková</Prijmeni>
  				<Prihl-jmeno>jiral</Prihl-jmeno>
  				<Pravomoce>2</Pravomoce>
  			</osoba>
  			<osoba id="3" Kod="0009">
  				<Jmeno>Petr</Jmeno>
  				<Prijmeni>Lichý</Prijmeni>
  				<Prihl-jmeno>lichp</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  			<osoba id="4" Kod="0010">
  				<Jmeno>Tomáš</Jmeno>
  				<Prijmeni>Vídeňský</Prijmeni>
  				<Prihl-jmeno>vidt</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  		</Pristupova-prava>
  </Oddeleni>

  <!-- Adresář NZ -->
  <Oddeleni Nazev="Neplatné zakázky" Disk="I">
  	<pocet-zaznamu-na-soubor>15</pocet-zaznamu-na-soubor>
  	<Popis>Špatně zadané zakázky</Popis>
  		<Pristupova-prava>
  			<osoba id="0" Kod="0000">
  				<Jmeno>Návštěvník</Jmeno>
  				<Prijmeni></Prijmeni>
  				<Prihl-jmeno>guest</Prihl-jmeno>
  				<Pravomoce>0</Pravomoce>
  			</osoba>
  				<osoba id="1" Kod="0001">
  				<Jmeno>Martin</Jmeno>
  				<Prijmeni>Beneš</Prijmeni>
  				<Prihl-jmeno>admin</Prihl-jmeno>
  				<Pravomoce>3</Pravomoce>
  			</osoba>
  		<osoba id="2" Kod="0011">
  				<Jmeno>Jitka</Jmeno>
  				<Prijmeni>Levá</Prijmeni>
  				<Prihl-jmeno>levaj</Prihl-jmeno>
  				<Pravomoce>2</Pravomoce>
  			</osoba>
  			<osoba id="3" Kod="0012">
  				<Jmeno>David</Jmeno>
  				<Prijmeni>Gregor</Prijmeni>
  				<Prihl-jmeno>gregd</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  			<osoba id="4" Kod="0013">
  				<Jmeno>David</Jmeno>
  				<Prijmeni>Sula</Prijmeni>
  				<Prihl-jmeno>sulad</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  		</Pristupova-prava>
  </Oddeleni>

  <!-- Adresář ZA -->
  <Oddeleni Nazev="Zákazníci"  Disk="K">
  	<pocet-zaznamu-na-soubor>25</pocet-zaznamu-na-soubor>
  	<Popis>Seznam zákazníků</Popis>
  		<Pristupova-prava>
  			<osoba id="0" Kod="0000">
  				<Jmeno>Návštěvník</Jmeno>
  				<Prijmeni></Prijmeni>
  				<Prihl-jmeno>guest</Prihl-jmeno>
  				<Pravomoce>0</Pravomoce>
  			</osoba>
  		<osoba id="1" Kod="0001">
  				<Jmeno>Martin</Jmeno>
  				<Prijmeni>Beneš</Prijmeni>
  				<Prihl-jmeno>admin</Prihl-jmeno>
  				<Pravomoce>3</Pravomoce>
  			</osoba>
  			<osoba id="2" Kod="0014">
  				<Jmeno>Anna</Jmeno>
  				<Prijmeni>Drapáková</Prijmeni>
  				<Prihl-jmeno>drapa</Prihl-jmeno>
  				<Pravomoce>2</Pravomoce>
  			</osoba>
  			<osoba id="3" Kod="0015">
  				<Jmeno>Jiří</Jmeno>
  				<Prijmeni>Lachman</Prijmeni>
  				<Prihl-jmeno>lachj</Prihl-jmeno>
  				<Pravomoce>2</Pravomoce>
  			</osoba>
  			<osoba id="4" Kod="0016">
  				<Jmeno>Vojtěch</Jmeno>
  				<Prijmeni>Babiš</Prijmeni>
  				<Prihl-jmeno>babiv</Prihl-jmeno>
  				<Pravomoce>1</Pravomoce>
  			</osoba>
  			  		</Pristupova-prava>
  </Oddeleni>
</Adresar_konfigurace>
